spring:
  application:
    name: opf-payments-consents-regulatory-api

logging:
  level:
    root: INFO            # Default logging level
    org.springframework: INFO
    org.springframework.web: DEBUG
    com.yourcompany: DEBUG